### ISSUE TITLE
Tessar

### ISSUE THREAD

**Issue by PFE3eme** [asagar60/TableNet-pytorch#1]
I found the project very interesting. 
but there is an error message. 
can you help me. 
![error](https://user-images.githubusercontent.com/11546703/137902681-84ad1c54-efa1-4563-9ec7-67b65c4b7634.PNG)

**Comment by asagar60** [comment]
Hi,
I may b wrong, but you are getting this error even after installing pytesseract ?
refer : https://pypi.org/project/pytesseract/
