### ISSUE TITLE
No densenet model found

### ISSUE THREAD

**Issue by maxschib** [asagar60/TableNet-pytorch#11]
Hi Arun,
I'm not able to find any model within this project, particularly densenet_config_4_model_checkpoint.pth.tar 

Could you please provide densenet_config_4_model_checkpoint.pth.tar at least ?

Thanks in advance

**Comment by asagar60** [comment]
refer : https://github.com/asagar60/TableNet-pytorch/issues/10#issuecomment-1528787302
