### ISSUE TITLE
I am new in deep learning, can anyone tell me how to finetune the model on my own dataset

### ISSUE THREAD

**Issue by Himanshi1811** [asagar60/TableNet-pytorch#4]

**Comment by jyotiyadav94** [comment]
@Himanshi1811 
did you find any way to train the model on your custom data ?

@asagar60 
Can you please provide some guidance on that ?

**Comment by asagar60** [comment]
hi, pls go through to blog post from the readme and let me know where you are stuck at

**Comment by jyotiyadav94** [comment]
Thanks you its very much clear after going through your post.
