### ISSUE TITLE
No module named 'model'

### ISSUE THREAD

**Issue by sks199** [asagar60/TableNet-pytorch#7]
I am facing this problem when trying to run on colab. I would be grateful if you could help me how to solve this.

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-1-d53e274eb2a2>](https://localhost:8080/#) in <module>
     13 import pytesseract
     14 from io import StringIO
---> 15 from model import TableNet

ModuleNotFoundError: No module named 'model'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by asagar60** [comment]
I understand where is this confusion. This project was built locally, hence running it colab is not suggested. training and testing scripts are both under "Training" directory. If you are executing Final.ipynb, load all training files in root directory.
