### ISSUE TITLE
Libraries installation and dependencies

### ISSUE THREAD

**Issue by favia96** [asagar60/TableNet-pytorch#8]
Hello, would you be able to provide a mini installation guide of the libraries and their dependencies? Thanks  :)

**Comment by sks199** [comment]
I am running into problems regarding the dependencies as well. When i try to run it on colab the first error i get is "model" not found when the line 
"from model import TableNet" runs.

**Comment by asagar60** [comment]
sure @favia96 . will try to add ASAP.

**Comment by favia96** [comment]
> sure @favia96 . will try to add ASAP.

Thank you!
