### ISSUE TITLE
Model link is dead please share another one

### ISSUE THREAD

**Issue by gamingflexer** [asagar60/TableNet-pytorch#9]

**Comment by asagar60** [comment]
pls check this one: https://drive.google.com/file/d/10fpOfOkPoj7ofzRBi27ni7E6oOAaMSKP/view?usp=sharing

**Comment by gamingflexer** [comment]
thanks a lot !

**Comment by abhayhk2001** [comment]
Hi, so i am using this link to download the model.
But i am getting pickling Error, Saying they Mark is not found. @gamingflexer were u able to run the model with this link ?

**Comment by gamingflexer** [comment]
<img width="1022" alt="Screenshot 2022-11-01 at 3 01 16 PM" src="https://user-images.githubusercontent.com/50608241/199203575-ef63152b-2440-4a8f-9051-46e3a35b1cca.png">
@abhayhk2001 ya same, @asagar60 can you please look into this.

**Comment by aayushee-gooru** [comment]
@asagar60 @abhayhk2001 @gamingflexer 
I also got a similar error wile using the model link.
Please share if you were able to deploy the model and any specific dependency versions to be used for deploying the code.
Thanks!
